on: 
    pull_request:
        types: [opened,reopened,synchronize]
  
jobs:
    snyk_fix_propagate:
        runs-on: ubuntu-latest
        name: Snyk testing stuff
        steps:
            - name: Testing
              id: snyk-job
              uses: snyk-tech-services/github-action-testing@master
              with:
                myToken: ${{ secrets.ghToken }}